FROM node:12.20.1

# Create app directory
WORKDIR /usr/src/app

COPY package.json .

RUN openssl rand 128 > sym_keyfile.key

RUN npm install --production

COPY src/ .

EXPOSE 8001

CMD ["node","server.js"]
