FROM node:12.20.1

# Create app directory

WORKDIR /mainInterface


COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

COPY tsconfig.json ./dist/
COPY tslint.json ./dist/

WORKDIR ./dist

EXPOSE 3000 
CMD node src/index.js
